### ISSUE TITLE
missing python2-setuptools 

### ISSUE THREAD

**Issue by R3C4M** [tedsluis/raspberry-pi-pwm-fan-control#1]
During build process via `podman build --tag gpio .` after STEP 2, there is an error about missing python2-setuptools: 

> STEP 3: RUN  dnf -y install libgpiod-utils python3-libgpiod swig python2 python2-setuptools python-setuptools python-devel python3-devel python-setuptools python3-setuptools unzip curl wget make gcc which 
No match for argument: python2-setuptools 
Package curl-7.79.1-1.fc35.aarch64 is already installed. 
Error: Unable to find a match: python2-setuptools 

after removing this package from Dockerfile it worked just fine. I think curl and mentioned python2-setuptools may be removed from STEP 3?

Raspberry Pi 4B with Ubuntu Server 21.10 64bit.

**Comment by tedsluis** [comment]
thnx for reporting this. fixed in: https://github.com/tedsluis/raspberry-pi-pwm-fan-control/commit/0bc79b44cbee5689bc978bae1c733f333abab198
